# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a57a5d6439d5e59adf442d43cc3af7968c270a3c36064a63f15028eb8a277de2fae4abcae3858b0edb83519807ae3956ae1ecd65bc97719a1d3cdb3ee0b1daa2

test:
  secret_key_base: 228b4c588f3a49f3da9df376b49e95f148732297e863951d5fc0c338cc0da7672b5c15dbf257e4b59655d21f09522e7dd1a9c53f8fb49f63f42b406811243147

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
